### ISSUE TITLE
[Question] Support for validation/transform plugins

### ISSUE THREAD

**Issue by ArturJS** [humanwhocodes/env#12]
@nzakas Many thanks for this great library!

I have a question regarding plans for future improvements to make this library way more useful for production grade applications than https://www.npmjs.com/package/dotenv .

What do you think about an idea to add support for validation plugins?

From what I know, there're plenty of validations libs, such as:
https://www.npmjs.com/package/yup
https://www.npmjs.com/package/runtypes
https://www.npmjs.com/package/joi
...
that provide great ability for runtime type checks and even more refined validation, such as custom validation rules using the arbitrary methods with, surely, refined interface data contracts for inputs and output, for better pluggability.

I think, as the next step, it would be awesome to have an ability to pass validation methods for custom validation rules.
Plus, I know at some extent it may introduce a bit more complexity for beginners, but for advanced usage it would be cool to add support for transform plugins which i.e. will allow end developers to define derived config parameters, making them happier whenever they encounter into such sort of difficulties.

**Comment by nzakas** [comment]
Thanks for the kind words.

I’m not sure I understand what you’re describing. Can you give an example use case? Keep in mind that environment variables are always strings, so I’m having trouble understanding what kind of validation or transforms you’re thinking of.

**Comment by ArturJS** [comment]
Yes, sure.
Regarding `transforms` method, let's say, we need to deserialize the data from `PORT` env var from string to number. 
```js
import { Env } from "@humanwhocodes/env";

const env = new Env({
  transforms(rawEnvs) {
    return {
      ...rawEnvs,
      PORT: Number(rawEnvs.PORT)
    };
  }
})
```

For envs validation, we can do the following:

```js
import { Env } from "@humanwhocodes/env";

const env = new Env({
  /**
   * @throws {TypeError}
   */
  validation(rawEnvs): void {
     const isNumberLike = rawEnvs.PORT === String(Number(rawEnvs.PORT));
     
     if (!isNumberLike) {
       throw new TypeError(`Invalid type of PORT=${rawEnvs.PORT}. Expected number.`)
     }
  }
})
```

Well, I know the validation and transform parts seem to be more relevant for something like '@humanwhocodes/env-config' (or so) rather than '@humanwhocodes/env'. Anyway, I just wanted to share the idea of how (just from my point of view) it may look like in future.

**Comment by nzakas** [comment]
Ah okay, thanks for explaining. I have thought of adding something like `getInt()`, `getBoolean()`, etc., that would automatically convert values. Aside from boolean, ints, and floats, I'm not sure there's a ton of value in converting environment variables to a different data type, so I'm not sold on the need for a generic transform mechanism.

In terms of validation, that seems beyond the scope of what I envisioned Env to be.

**Comment by ArturJS** [comment]
Ok, I got the point.
Many thanks for sharing your vision of the future of `@humanwhocodes/env`!

**Comment by nzakas** [comment]
You're welcome. :)
