### ISSUE TITLE
How to use require and first together?

### ISSUE THREAD

**Issue by renatoargh** [humanwhocodes/env#13]
I have the case where I have two defaults, if none of them are present I want an exception to happen, for example:

```
// this is just an example with imaginary code (from the tests I know it does work)
const project = env.require(['FIRST_ENV', 'SECOND_ENV'])
```

The `project` variable, in this case, would also benefit because it could be typed as a `string` and not as a `string | undefined` as when I use just `.require`

**Comment by renatoargh** [comment]
By the way, great work! Congrats :)

**Comment by nzakas** [comment]
That's not currently supported. I think you're looking for something like a `requireFirst()` method?

**Comment by renatoargh** [comment]
Yeah, that name makes sense! I had the same idea :) 

I think it is important to make sure that the type returned is `T` and not `T | undefined` so that we don't have to perform any checks afterward (since it is either there or an exception was thrown)

Thanks for the quick reply

**Comment by nzakas** [comment]
That's a good point. I'm open to adding a new method, I just need to think through the naming and function signature a bit.
