### ISSUE TITLE
TypeScript cannot find typings for CommonJS version of this package

### ISSUE THREAD

**Issue by krutoo** [humanwhocodes/env#136]
Hi, I am trying to use this library with TypeScript. In my case **I need to get CommonJS output from TypeScript source code**.

I also tried using a config similar to the one in this project:

```json
{
  "extends": "@tsconfig/node16/tsconfig.json",
  "compilerOptions": {
    "allowJs": true,
    "checkJs": true
  }
}
```

But in case of `.ts` and `.cjs` files I have error:

```
The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@humanwhocodes/env")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"` to 'stackblitz:/package.json'.(1479)
```

Here is an example with reproduction:
https://stackblitz.com/edit/typescript-node-hpq7zy?file=src%2Findex.ts

In this example I also added another dual (ESM+CJS) package for comparison.

![Screenshot](https://github.com/humanwhocodes/env/assets/13140130/6d02c36c-1008-4b07-af93-b9b06198d51d)

For some reason TypeScript can find declarations for ESM version of `humanwhocodes/env` but cannot find same declarations for CommonJS

**You can see problem in `.ts` and in `.cjs` files** - just run `npm run check`

### Additional information

- I can't just change extension to `.mts` and I also can't just add `"type": "module"` for my project, I need exactly CommonJS output and that is why I configured TypeScript this way

- With provided TS config `import` will be replaced by `require` and it is exactly what I needed for output code

- Package `humanwhocodes/env` works with CommonJS, problem is just with TypeScript type checking.

**Comment by nzakas** [comment]
Your `fetch-tools` package isn't helpful because it's built with `dnt` so I can't actually tell what it's doing.

We already have tests covering loading in CommonJS and ESM, along with tests for types here:
https://github.com/humanwhocodes/env/tree/main/tests

If you'd like more help, you're going to have to more research on your end:

1. Create a test in this repo that fails
2. Find another package that exports both `require` and `import` using a static `package.json` and show that it does (or doesn't) produce the same error.

This current error message still seems like it's more an error with your setup than with the package, so if you can come up with a different error, feel free to share it.

**Comment by krutoo** [comment]
> Your `fetch-tools` package isn't helpful because it's built with `dnt` so I can't actually tell what it's doing.

@nzakas you can see generated `package.json` here: https://www.npmjs.com/package/@krutoo/fetch-tools?activeTab=code

**Comment by krutoo** [comment]
> We already have tests covering loading in CommonJS and ESM, along with tests for types here:
> https://github.com/humanwhocodes/env/tree/main/tests

@nzakas I forked `humanwhocodes/env` and just remove `type` field from `package.json` here:
https://github.com/humanwhocodes/env/blob/main/tests/fixtures/ts-project-module-nodenext/package.json

And tests still pass, despite the fact that there is an error in the IDE:
![image](https://github.com/humanwhocodes/env/assets/13140130/97f3b96a-3ff9-4e4a-b8f7-50755b43c7da)

**Comment by krutoo** [comment]
> 1. Create a test in this repo that fails

@nzakas I created PR with example:
https://github.com/humanwhocodes/env/pull/137
